### ISSUE TITLE
SubLink node doesn't emit operName field

### ISSUE THREAD

**Issue by zhm** [pganalyze/libpg_query#10]
In the V2 output, `operName` is missing from `SubLink` nodes. This is required to differentiate `IN` from `ANY` in sublinks with `subLinkType` of 2. I'm not sure what's happening because I do see operName defined in the data files.

(Yet another corner case from the postgres test files :)

Test query:

```
select sum(unique1) FILTER (WHERE unique1 IN (SELECT unique1 FROM onek where unique1 < 100)) FROM tenk1
```

V2 Output:

https://gist.github.com/zhm/29ae8af205f135596fd024172121f220

V1 Output:

https://gist.github.com/zhm/c6c23e9889011d617eb0a4163a888779

**Comment by zhm** [comment]
Upon further investigation I'm not sure this is a bug. In fact I think this behavior is actually a _fix_ in symmetry compared to the V1 output.

The following queries return the identical AST in the V1 output, and in V2 they differ in the presence of the `operName` attribute. I believe they are semantically identical, but having the `operName` allows a deparser to preserve the original syntax. I think this issue can be closed.

``` sql
SELECT 1 WHERE 2 IN (SELECT 3)
```

``` sql
SELECT 1 WHERE 2 = ANY (SELECT 3)
```

**Comment by lfittl** [comment]
@zhm Yeah, this seems to be a change that happened in PostgreSQL: https://github.com/postgres/postgres/commit/56be925e4b8f5b1c0e6716ca5cbe0360d1229f50#diff-9bbb46a2828358f31d416900ceb0ef69R11473 (V2 uses 9.5, the old version was 9.4)

The commit message and comments make me think that you can assume that `operName = null` and `subLinkType = ANY_SUBLINK` means that it was an `IN (..)`. In the case of `ANY` it would have `operName = "="`.

Diffing the outputs between an `IN (..)` and `= ANY (..)` seems to prove that:

``` diff
@@ -32,11 +32,6 @@
                  "location": 34
          }
  },
+ "operName": [{
+         "String": {
+                 "str": "="
+         }
+ }],
  "subselect": {
          "SelectStmt": {
                  "targetList": [{
```

**Comment by lfittl** [comment]
Closing this for now, since its not an actual issue, but rather by intention when going from PostgreSQL 9.4 to 9.5.
