### ISSUE TITLE
deparser question

### ISSUE THREAD

**Issue by hcheng2002cn** [pganalyze/libpg_query#102]
may i know if pg_query_deparse.c is generated by script or write by human ? how to test deparser ?

Thanks
hong

**Comment by lelit** [comment]
deparse.c has been written by Lukas, there's no way to automatically get the reverse of LEX&YACC outcome.
To test it, it get fed with a "regression test" corpus of valid statements, basically asserting that it gives back the same statement (minus whitespace and the like).

**Comment by lfittl** [comment]
Thats correct - its handwritten (by myself) based on parsing and deparsing all Postgres regression tests, plus a few statement types that are not covered in the tests.

**Comment by hcheng2002cn** [comment]
Thanks for information
