### ISSUE TITLE
SIGSEGV when passing invalid protobuf for deparse

### ISSUE THREAD

**Issue by wesselvdv** [pganalyze/libpg_query#129]
When passing a valid protobuf, but invalid sql statement (RawStmt without Stmt) to pg_query_deparse_protobuf you'll get a SIGSEGV. 

I created a PR that fixes it. #128

**Comment by lfittl** [comment]
Closing this since the linked PR is merged (https://github.com/pganalyze/libpg_query/pull/128) - we'll likely stamp a new tagged release soon that includes this as well.

Thanks for the contribution!
