### ISSUE TITLE
10-latest: A_Const Float from bigint literal

### ISSUE THREAD

**Issue by jgm-ktg** [pganalyze/libpg_query#139]
```
"A_Const": {
    "location": 84,
    "val": {
        "Float": {
            "str": "1652741402000000000"
        }
    }
}

```
```
thedb=> select pg_typeof(1652741402000000000);
 pg_typeof 
-----------
 bigint
(1 row)

```
Is this correct that a bigint is marked as Float?

**Comment by lfittl** [comment]
@jgm-ktg Yep, thats expected. Its an implementation detail of how the Value node works - it uses "Float" to represent the fact that it stored the value as a string internally (in the str field), vs "Integer" when it uses the integer field (in the ival field).

See https://github.com/postgres/postgres/blob/REL_10_STABLE/src/include/nodes/value.h#L36
