### ISSUE TITLE
PgQueryError not zero'd on allocation

### ISSUE THREAD

**Issue by zhm** [pganalyze/libpg_query#14]
I think the new `funcname` field is never being filled in, and since the struct isn't zero'd it contains garbage. I was seeing segfaults when trying to use the new version, which turned out to be me forgetting to update the header file, but then I was still getting them when adding support for the new field in the errors.

**Comment by lfittl** [comment]
@zhm Mmmh, you might be right - let me fix that.

**Comment by lfittl** [comment]
@zhm Ok, so I think https://github.com/lfittl/libpg_query/commit/e243608a92370b666bae7e74fdc60dcd6a53f9ab, as well as https://github.com/lfittl/libpg_query/commit/9b674b9e944c4256ba4cdbcef96c3fb28d2f2228 should fix it for you.

Let me know if that works!

**Comment by zhm** [comment]
Fixed!
