### ISSUE TITLE
Unable to parse COPY statements

### ISSUE THREAD

**Issue by wesselvdv** [pganalyze/libpg_query#161]
Trying to parse the following query will error with a `scanner_yyerror` in file `scan.l`

```sql
COPY bool_test FROM STDIN NULL 'null';
TRUE	null	FALSE	null
FALSE	TRUE	null	null
null	TRUE	FALSE	null
\.
```

**Comment by lelit** [comment]
I think that this statement is handled in a peculiar way by `psql` (at least, that's what I concluded in a similar [pglast issue](https://github.com/lelit/pglast/issues/43)).

**Comment by lfittl** [comment]
Yup - as @lelit noted, this is psql syntax and not something the server-side parser can support.

**Comment by wesselvdv** [comment]
Yes, this seems to be obvious in hindsight.
