### ISSUE TITLE
sql parsing error on alter index with numerical column reference

### ISSUE THREAD

**Issue by wesselvdv** [pganalyze/libpg_query#162]
The following sql snippet:

```sql
CREATE TABLE attmp (
	initial 	int4
);

ALTER TABLE attmp ADD COLUMN a int4;

ALTER TABLE attmp ADD COLUMN b name;

ALTER TABLE attmp ADD COLUMN c text;

ALTER TABLE attmp ADD COLUMN d float8;

ALTER TABLE attmp ADD COLUMN e float4;

CREATE INDEX attmp_idx ON attmp (a, (d + e), b);

ALTER INDEX attmp_idx ALTER COLUMN 0 SET STATISTICS 1000; -- errors on this statement
```

Errors with the following:

```json
{
    "fileName": "gram.y",
    "functionName": "base_yyparse",
    "lineNumber": 2270,
    "cursorPosition": 3294,
    "context": null
  }
```

**Comment by lelit** [comment]
It's not clear how you fed the above to the parser, but trying this out with `pglast` I obtain the following:
```
$ pgpp -S "ALTER INDEX attmp_idx ALTER COLUMN 0 SET STATISTICS 1000"

column number must be in range from 1 to 32767, at index 35
```

and indeed the `column_number` in `ALTER INDEX ... ALTER COLUMN column_number ...` is [documented](https://www.postgresql.org/docs/13/sql-alterindex.html) as _“The ordinal number refers to the ordinal (left-to-right) position of the index column”_. In other words, it starts from 1, not 0.

**Comment by wesselvdv** [comment]
Oh, you're right. I should've tried the non-zero one.
