### ISSUE TITLE
Incorrect "CREATE SCHEMA IF NOT EXISTS cannot include schema elements"

### ISSUE THREAD

**Issue by wesselvdv** [pganalyze/libpg_query#164]
Snippet of SQL where this error is thrown:

```sql
CREATE SCHEMA test_ns_schema_1

    CREATE UNIQUE INDEX abc_a_idx ON abc (a)

    CREATE VIEW abc_view AS
    SELECT
        a + 1 AS a,
        b + 1 AS b
    FROM
        abc

    CREATE TABLE abc
    (
        a SERIAL,
        b INT UNIQUE
    );
```

I was able to execute this just fine on PostGres 14

**Comment by lelit** [comment]
The snippet above does not contain `IF NOT EXISTS`: accordingly to the [documentation](https://www.postgresql.org/docs/13/sql-createschema.html) the syntax does not allow the presence of both that option and schema elements.

**Comment by wesselvdv** [comment]
It's interesting though that I am able to execute the example without issues.

**Comment by lelit** [comment]
Strange indeed: I can only test against PG 14 and I obtain:
```
test=# CREATE SCHEMA if not exists test_ns_schema_1
test-#
test-#     CREATE UNIQUE INDEX abc_a_idx ON abc (a)
test-# ``
test-#     CREATE VIEW abc_view AS
test-#     SELECT
test-#         a + 1 AS a,
test-#         b + 1 AS b
test-#     FROM
test-#         abc
test-#
test-#     CREATE TABLE abc
test-#     (
test(#         a SERIAL,
test(#         b INT UNIQUE
test(#     );
ERROR:  CREATE SCHEMA IF NOT EXISTS cannot include schema elements
LINE 2:     CREATE UNIQUE INDEX abc_a_idx ON abc (a)
            ^
```

**Comment by wesselvdv** [comment]
It might be due to the fact that I am executing this in Intellij:

```
postgres.public> CREATE SCHEMA test_ns_schema_1
                 
                     CREATE UNIQUE INDEX abc_a_idx ON abc (a)
                 
                     CREATE VIEW abc_view AS
                     SELECT
                         a + 1 AS a,
                         b + 1 AS b
                     FROM
                         abc
                 
                     CREATE TABLE abc
                     (
                         a SERIAL,
                         b INT UNIQUE
                     )
[2022-11-16 16:05:32] completed in 29 ms
```

**Comment by lelit** [comment]
Maybe you must explicitly commit the transaction? In any case, against which version of PG?

**Comment by lelit** [comment]
But again, the code you show **does not** contain `IF NOT EXISTS`...

**Comment by wesselvdv** [comment]
Oh, I see what you mean. My issue is about the fact that the parser is giving me this error even though I am not including `IF NOT EXISTS` hence the incorrectness of it.

EDIT:

Looks like I found the culprit. Me. I did have an incorrect one in my code, which I missed. Apologies!
