### ISSUE TITLE
limits.h in pg_query_deparse.c not necessary?

### ISSUE THREAD

**Issue by yrashk** [pganalyze/libpg_query#176]
My quick experiment shows that removing the include for `limits.h` does not affect pg_query_deparse.c

Perhaps it can be removed? I can prepare PRs for every branch if necessary.

**Comment by lfittl** [comment]
You might be right - the deparsing code went through a lot of iterations before the initial release, and that might be a leftover from a prior iteration.

FWIW, generally we focus on the latest branch and don't backpatch unless its something more severe (its overhead to stamp releases on the old branches, etc). So if you want to prepare a PR for `15-latest` that would be ideal.
