### ISSUE TITLE
Escape JSON strings in error message

### ISSUE THREAD

**Issue by kucerm2** [pganalyze/libpg_query#18]
PgQueryPlpgsqlParseResult.error and PgQueryParseResult.error contains quotation marks in message string without escape. This make impossible parse result as JSON.

Sample:
{ "error" : {"cursorpos" : 0 , "filename" : "pl_gram.y", "funcname" : "plpgsql_yyparse", "lineno" : 716, "message" : "variable "contract_case_split_supplier_contracts.caller_id" does not exist"}}

Correct version:
{ "error" : {"cursorpos" : 0 , "filename" : "pl_gram.y", "funcname" : "plpgsql_yyparse", "lineno" : 716, "message" : "variable \"contract_case_split_supplier_contracts.caller_id\" does not exist"}}

**Comment by lfittl** [comment]
@kucerm2 Thanks for the report, that does indeed seem like a bug.

Do you want to try making a pull request, or do you prefer if I fix it? (either works)

**Comment by kucerm2** [comment]
@lfittl Yes, I try it ;)

**Comment by kucerm2** [comment]
Sorry, I make JSON in my wrapper. This issue is faux pas.

**Comment by lfittl** [comment]
@kucerm2 Ah, no worries - happy that you've found the issue.

I'm curious, what are you building on top of libpg_query?

**Comment by kucerm2** [comment]
@lfittl We are implementing service for PostgreSQL intellisense and refactoring database(rename user types, tables, columns, etc.) through tables to procedure body. But your parser is not ideal because generated syntactic tree is focused for execution :/

**Comment by lfittl** [comment]
@kucerm2 Yeah, that makes sense - the parser matches what PostgreSQL does internally (its extracted from there), hence the focus on execution.
