### ISSUE TITLE
Making query deparsing indepenently usable

### ISSUE THREAD

**Issue by yrashk** [pganalyze/libpg_query#180]
I am using `libpg_query`'s deparsing functionality in [Omnigres](https://github.com/omnigres/omnigres/tree/master/extensions/omni_sql). However, since it's primarily a collection of extensions, the primary use case of libpg_query itself doesn't quite fit. I don't use it independently of Postgres, I am supplementing Postgres with the deparsing functionality when I need to manipulate or analyze queries.

I've done a fairly simple job integrating deparsing code (as seen above) but going forward, every time deparsing changes, I'd need to repeat a few steps, which is not ideal:

* Getting rid of pg_query_* API related stuff as it is not relevant
* Exposing `deparseRawStmt` function

I wonder if you'd be open to a patch that, for example, makes deparsing turn off pg_query_ and expose `deparseRawStmt` conditionally (perhaps opt-in to avoid the exposure of this throughout libpg_query itself)?

This way I can take the deparsing code and simply compile it with `-DISOLATED_PGQUERY_DEPARSING` and updating this dependency will be as simple as grabbing a new version of the file.

Happy to prepare a PR if this sounds like a good start.

**Comment by lfittl** [comment]
@yrashk Interesting question - I do think we can improve the situation here, though I wonder if a better way to look at this wouldn't be to make the deparser its own standalone unit that can easily be repurposed like this (i.e. not necessarily introducing a define, but rather just have a single ".c" file that you can vendor).

Do I understand correctly that the only difference between your `deparse_15.c` and `pg_query_deparse.c` are the fact that `deparseRawStmt` is exported (not static), and that you've dropped `pg_query_deparse_protobuf` and `pg_query_free_deparse_result`?

**Comment by yrashk** [comment]
> @yrashk Interesting question - I do think we can improve the situation here, though I wonder if a better way to look at this wouldn't be to make the deparser its own standalone unit that can easily be repurposed like this (i.e. not necessarily introducing a define, but rather just have a single ".c" file that you can vendor).

I am fine with a separate single .c file, too! In fact, I would prefer that.

> Do I understand correctly that the only difference between your `deparse_15.c` and `pg_query_deparse.c` are the fact that `deparseRawStmt` is exported (not static), and that you've dropped `pg_query_deparse_protobuf` and `pg_query_free_deparse_result`?

Pretty much.

**Comment by lfittl** [comment]
@yrashk Excellent - just gave this a try in #183 

One detail question I have: To follow what the Postgres project usually does, I added a `postgres.h` include [at the start of the file](https://github.com/pganalyze/libpg_query/blob/e67e440fad67a3314a310b8c649db46ef208c6cf/src/postgres_deparse.c#LL1C2-L1C9) -- but I don't have a strong opinion on that.

The alternative would be to include `stdint.h` and `sys/types.h`, to have type definitions like `uint32`. I don't think we're using anything else from `postgres.h` that isn't included explicitly. Preferences for your use case?
