### ISSUE TITLE
wishlist: function to reuse the tokens from pg_query_scan for parsing

### ISSUE THREAD

**Issue by SKalt** [pganalyze/libpg_query#185]
I'm investigating how to create a concrete syntax tree using libpg_query.  I'd like to be able to call `pg_query_scan` to get tokens with their locations, then call a function like `pg_query_parse_tokens` to avoid re-scanning the entire query during parsing. This would be a nice-to-have since re-scanning the query isn't deal-breakingly expensive.

I think implementing a function like `pg_query_parse_tokens` would require
1. making a copy of [`raw_parser`](https://github.com/postgres/postgres/blob/c8e1ba736b2b9e8c98d37a5b77c4ed31baf94147/src/backend/parser/parser.c#L49) with a scanner as an extra argument 
2.  figuring out how to create a mock-scanner ([`core_yyscan_t`](https://github.com/postgres/postgres/blob/c8e1ba736b2b9e8c98d37a5b77c4ed31baf94147/src/include/parser/scanner.h#L119)), which seems relatively difficult.

**Comment by lfittl** [comment]
Thanks for the wishlist request!

> making a copy of [raw_parser](https://github.com/postgres/postgres/blob/c8e1ba736b2b9e8c98d37a5b77c4ed31baf94147/src/backend/parser/parser.c#L49) with a scanner as an extra argument

I think this is a bit of a deal breaker, since it adds another patch/code copy for us to maintain for each new Postgres release.

> figuring out how to create a mock-scanner ([core_yyscan_t](https://github.com/postgres/postgres/blob/c8e1ba736b2b9e8c98d37a5b77c4ed31baf94147/src/include/parser/scanner.h#L119)), which seems relatively difficult.

I don't follow this part of the idea - can you describe more what the mock-scanner would do in this case, that the existing `pg_query_scan` function doesn't make available?

**Comment by SKalt** [comment]
> I think this is a bit of a deal breaker, since it adds another patch/code copy for us to maintain for each new Postgres release.

Completely understandable! Thanks for the quick reply in any case.

> > figuring out how to create a mock-scanner ([core_yyscan_t](https://github.com/postgres/postgres/blob/c8e1ba736b2b9e8c98d37a5b77c4ed31baf94147/src/include/parser/scanner.h#L119)), which seems relatively difficult.
>
> I don't follow this part of the idea

I was picturing constructing something that `base_yyparse(yyscanner)` could accept that would yield tokens from the array of already-scanned tokens.
