### ISSUE TITLE
PLPSQL parser not recognize procedure parameters in declare statement

### ISSUE THREAD

**Issue by kucerm2** [pganalyze/libpg_query#19]
This is valid PLPSQL script, but pg_query_free_plpgsql_parse_result returns error.

Input:
`CREATE OR REPLACE FUNCTION cs_fmt_browser_version(v_name varchar, v_version varchar)
 RETURNS varchar AS $$
 DECLARE
  _a int;
  _v_name_alias ALIAS FOR $0;
 BEGIN 
  IF v_version IS NULL THEN 
   RETURN v_name; 
  END IF;

  RETURN v_name || '/' || v_version; 
 END; $$ LANGUAGE plpgsql;`

Error output:
variable "$0" does not exist

This seems like statement parser hasn't a procedure parameters list.

**Comment by lfittl** [comment]
@kucerm2 Yes, this is a known bug in the PL/pgSQL parser right now - fixing it requires a bit of hacking, which is why I haven't done it yet.

Is this a blocking issue for your project?

**Comment by rafaelthca** [comment]
Hi Lukas,

Thanks for the amazing project.

Are you planning to implement this? I am using your library in a simple plpgsql debugger and accessing those parameters would be nice. I could try to implement that if you are too busy.

Rafael.

**Comment by lfittl** [comment]
@rafaelthca As written in #38 help on the PL/pgSQL part of the library would be very welcome :)
