### ISSUE TITLE
PostgreSQL grammar online

### ISSUE THREAD

**Issue by mingodad** [pganalyze/libpg_query#209]
We can test the `PostgreSQL` grammar online at https://mingodad.github.io/parsertl-playground/playground/ (select `PostgreSQL parser (be patient)` from `Examples` then click `Parse` to see a parser tree for the content in `Input source` editor).

I hope it can help debug/develop/test `Yacc/Lex` grammars like the one from `PostgreSQL` used by this project.

The main repository is here https://github.com/mingodad/parsertl-playground .

There is there grammars for:
- SQLite3
- MySQL
- Tidb
- ArangoDB
- CG-CQL
- TDEngine
- Tradofion
- Vitess

Any feedback is welcome !

**Comment by lfittl** [comment]
Interesting project!

However it appears you are not utilizing libpg_query though, but rather are importing the raw Postgres grammar files? (https://github.com/mingodad/parsertl-playground/blob/main/playground/postgres16.g)

Whilst I think this is neat, it does seem offtopic for this project, so I will close this issue for now.
