### ISSUE TITLE
Make subquery aliases optional in the FROM clause

### ISSUE THREAD

**Issue by mehranmeidani** [pganalyze/libpg_query#218]
This commit on the official postgres repo makes subquery aliases optional : https://github.com/postgres/postgres/commit/bcedd8f5fce0b69970cf0cee7bca560833d05869

However, libpg_query still requires aliases for subqueries (src_backend_parser_gram.c:44351)

I spend sometime understand how to update the grammar but couldn't figure it out.

**Comment by lfittl** [comment]
@mehranmeidani Thanks for reaching out!

libpg_query is currently still on Postgres 15, which does not have the commit you referenced - that was added in Postgres 16, and we can expect that once we upgrade the parser (we're currently planning that out) this would also be supported.

**Comment by mehranmeidani** [comment]
I see. We need this to parse AWS Redshift queries. If I drop the error part in the `src_backend_parser_gram` file, will it work? Can you tell me where else should I change for a temp fix?

**Comment by lfittl** [comment]
This should be resolved now that the Postgres 16 version has been officially released (v5.0.0).
