### ISSUE TITLE
Support for PostgreSQL 16

### ISSUE THREAD

**Issue by lelit** [pganalyze/libpg_query#220]
In issue #218 there is a mention to upgrading the parser to PostgreSQL 16: is there a plan for that?

See also https://github.com/lelit/pglast/issues/137

Thanks&bye!

**Comment by df7cb** [comment]
Debian wants to finish the transition to PG16 and would profit from libpg-query being upgraded. Thanks!

**Comment by msepga** [comment]
We're working on this currently, and hope to have a release out in the next week or two 🙂

**Comment by lelit** [comment]
Great, thanks!

**Comment by lfittl** [comment]
Completed via https://github.com/pganalyze/libpg_query/pull/225 last week and tagged as 16-5.0.0.
