### ISSUE TITLE
Does this project depend on protobuf?

### ISSUE THREAD

**Issue by kovmir** [pganalyze/libpg_query#238]
Is [`protobuf-c`](https://github.com/protobuf-c/protobuf-c) a dependency of this project?

**Comment by lfittl** [comment]
Yes, Protobuf is utilized as a way to translate the internal C structs that Postgres maintains into something that can be easily consumed by other programming languages in a structured form.

Note that technically we bundle `protobuf-c` as part of the source code, so you don't need to have it installed on the system.
