### ISSUE TITLE
Install fails on CentOS 6.6

### ISSUE THREAD

**Issue by NelsonScott** [pganalyze/libpg_query#24]
Server: CentOS release 6.6 (Final)

```
[deploy@hamming tmp]$ git clone -b 9.5-latest git://github.com/lfittl/libpg_query
[deploy@hamming current]$ cd /tmp/
[deploy@hamming libpg_query]$ make
compiling src/pg_query.c
In file included from ./src/postgres/include/postgres.h:47,
                 from src/pg_query_internal.h:4,
                 from src/pg_query.c:2:
./src/postgres/include/c.h:298: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int128’
./src/postgres/include/c.h:299: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘uint128’
make: *** [src/pg_query.o] Error 1
```

**Comment by lfittl** [comment]
I believe this might be because your `gcc` version doesn't support 128bit Integers properly.

This is one of the things which PostgreSQL itself handles without issue, but where this library takes a short cut (by configuring for a certain minimum architecture/compiler).

Whats your use case for libpg_query - are you looking to use this on a server as part of some tooling?

**Comment by NelsonScott** [comment]
Hi @lfittl thanks for helping me with this.  

I originally was trying to install the pg_query gem on a CentOS server, but was getting this error during a bundle install

```
** [out :: <sever-name>] Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
** [out :: <sever-name>] 
** [out :: <sever-name>] /usr/local/rvm/rubies/ruby-2.1.3/bin/ruby extconf.rb
** [out :: <sever-name>] compiling src/pg_query.c
** [out :: <sever-name>] In file included from ./src/postgres/include/postgres.h:47,
** [out :: <sever-name>] from src/pg_query_internal.h:4,
** [out :: <sever-name>] from src/pg_query.c:2:
** [out :: <sever-name>] ./src/postgres/include/c.h:298: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int128’
** [out :: <sever-name>] ./src/postgres/include/c.h:299: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘uint128’
** [out :: <sever-name>] make: *** [src/pg_query.o] Error 1
** [out :: <sever-name>] cp: cannot create regular file `./../../spec/files/': No such file or directory
** [out :: <sever-name>] creating Makefile
** [out :: <sever-name>] 
** [out :: <sever-name>] make "DESTDIR=" clean
** [out :: <sever-name>] 
** [out :: <sever-name>] make "DESTDIR="
** [out :: <sever-name>] compiling pg_query_ruby.c
** [out :: <sever-name>] pg_query_ruby.c: In function ‘pg_query_ruby_parse’:
** [out :: <sever-name>] pg_query_ruby.c:80: warning: ISO C90 forbids mixed declarations and code
** [out :: <sever-name>] pg_query_ruby.c: In function ‘pg_query_ruby_normalize’:
** [out :: <sever-name>] pg_query_ruby.c:99: warning: ISO C90 forbids mixed declarations and code
** [out :: <sever-name>] pg_query_ruby.c: In function ‘pg_query_ruby_fingerprint’:
** [out :: <sever-name>] pg_query_ruby.c:115: warning: ISO C90 forbids mixed declarations and code
** [out :: <sever-name>] linking shared-object pg_query/pg_query.so
** [out :: <sever-name>] /usr/bin/ld: cannot find -lpg_query
** [out :: <sever-name>] collect2: ld returned 1 exit status
** [out :: <sever-name>] make: *** [pg_query.so] Error 1
** [out :: <sever-name>] 
** [out :: <sever-name>] make failed, exit code 2
```

Since it seemed to be an issue with lpg_query I came looking here. 
We're using:
ruby 2.1.3p242
CentOS release 6.6 (Final)

Let me know if more environment info would help.

**Comment by lfittl** [comment]
Hi @NelsonScott - that makes sense.

It would help if you could share `gcc --version` to confirm my assumption. I think we might need to do some trickery to support older versions, but worth giving a try. Thanks!

**Comment by NelsonScott** [comment]
@lfittl sure thing
```
 gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by NelsonScott** [comment]
@lfittl is it possible to upgrade gcc or use a work around to install libpg_query without upgrading CentOS? I don't know too much about the compiler

**Comment by lfittl** [comment]
@NelsonScott Its something we should be able to fix in the library, and I'll take a look at that sometime in the next few weeks - unfortunately very busy at the moment.

Outside of that, upgrading gcc would also fix it. I'm not that familiar with CentOS itself, so can't advise how to install a newer gcc on your system.

**Comment by NelsonScott** [comment]
@lfittl I got it to work, followed this guide's instructions https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b the post by @stephenturner
Then add `source /opt/rh/devtoolset-3/enable` to bashrc to make the change permanent. 

Thanks for pointing me in the right direction.

**Comment by lfittl** [comment]
Ok - great!

I'll close this one for now, since its unlikely I'll find the time to fix this in the near future. Hopefully this problem will solve itself as older compilers go extinct :)
