### ISSUE TITLE
Build fails on 32 bit system

### ISSUE THREAD

**Issue by herwinw** [pganalyze/libpg_query#26]
```
qnet@devel-o9:~/tmp/libpg_query$ CC=/usr/bin/gcc-4.9 make
compiling src/pg_query.c
In file included from ./src/postgres/include/c.h:53:0,
                 from ./src/postgres/include/postgres.h:47,
                 from src/pg_query_internal.h:4,
                 from src/pg_query.c:2:
./src/postgres/include/pg_config.h:725:24: error: ‘__int128’ is not supported for this target
 #define PG_INT128_TYPE __int128
                        ^
./src/postgres/include/c.h:298:9: note: in expansion of macro ‘PG_INT128_TYPE’
 typedef PG_INT128_TYPE int128;
         ^
In file included from ./src/postgres/include/postgres.h:47:0,
                 from src/pg_query_internal.h:4,
                 from src/pg_query.c:2:
./src/postgres/include/c.h:298:24: warning: type defaults to ‘int’ in declaration of ‘int128’ [-Wimplicit-int]
 typedef PG_INT128_TYPE int128;
                        ^
In file included from ./src/postgres/include/c.h:53:0,
                 from ./src/postgres/include/postgres.h:47,
                 from src/pg_query_internal.h:4,
                 from src/pg_query.c:2:
./src/postgres/include/pg_config.h:725:24: error: ‘__int128’ is not supported for this target
 #define PG_INT128_TYPE __int128
                        ^
./src/postgres/include/c.h:299:18: note: in expansion of macro ‘PG_INT128_TYPE’
 typedef unsigned PG_INT128_TYPE uint128;
                  ^
Makefile:73: recipe for target 'src/pg_query.o' failed
make: *** [src/pg_query.o] Error 1
```

**Comment by lfittl** [comment]
Hi @herwinw!

The library code is currently pre-configured for 64-bit systems only, mostly to avoid having a dependency on autoconf for the typical users.

Whats your use case - are you looking to use this library directly, or one of the helper libraries in a scripting language?

**Comment by herwinw** [comment]
I got a review request for a change in a SQL file, which contained both indentation fixes and real changes, and I wanted to simplify the review. Due to legacy reasons (and I surely don't mean lazyness...) we're still at 32 bit.

Actually, the specific use case was solved by returning the review request to keep it limited to only one change per commit. But still, it might be useful to have a tool that could validate if the changes made are only syntactic, so a code review and test could be skipped. (I often do this with perl code: use B::Deparse to regenerate both the old and new code: if this is equal, the code is equal too)

**Comment by herwinw** [comment]
(that was the wrong button)

**Comment by lfittl** [comment]
@herwinw That makes sense, and is a good use case for the library :)

The easiest way to proceed would be to test if its just the 128bit integer type thats the problem, or if we need to do more than that to support 32bit.

If you could download a copy of the PostgreSQL source (any version would work, but 9.5 is what this library is currently based on - e.g. `git clone https://github.com/postgres/postgres.git -b REL9_5_STABLE --depth=1`) and then run `./configure` it should generate a file in `src/include/pg_config.h`.

For this library the generated file looks like this: https://github.com/lfittl/libpg_query/blob/9.5-latest/src/postgres/include/pg_config.h#L725

Could you check what the file looks like on your 32-bit system, in particular the line about PG_INT128_TYPE?

**Comment by herwinw** [comment]
```c
/* Define to the name of a signed 128-bit integer type. */
/* #undef PG_INT128_TYPE */
```

There are no other references to 128 in the file.

**Comment by lfittl** [comment]
@herwinw Ah, that might make it easier then - could you check if you do a similar thing in libpg_query (i.e. comment the definition line out) whether that fixes compilation for you?

**Comment by lfittl** [comment]
Fixed via https://github.com/lfittl/libpg_query/commit/6b0961891b0c930887e7062415d5818e1537b92c
