### ISSUE TITLE
how to generate src_backend_*.c files from flex&bison source file

### ISSUE THREAD

**Issue by cjbd** [pganalyze/libpg_query#266]
Hello, is there a guide or script to generate all those `src_backend_*.c` files from flex&bison source code like `scan.l`, `grammar.y`?
thanks!

**Comment by lfittl** [comment]
@cjbd Those files are automatically extracted from the Postgres source, via libclang. See scripts/extract_source.rb and [extract_source](https://github.com/pganalyze/libpg_query/blob/16-latest/Makefile#L1490) Makefile target.

Out of curiosity, what's the use case where you're trying to generate these files?

**Comment by cjbd** [comment]
@lfittl thanks a lot! i just started learning sql parsing, i thought all parser code was supposed to be generated by flex&bison
