### ISSUE TITLE
extract_source failed on Linux

### ISSUE THREAD

**Issue by BugsGuru** [pganalyze/libpg_query#271]
### env
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
sed (GNU sed) 4.8
GNU Make 4.3

### error
branch: `fce106a (HEAD -> 16-latest, tag: 16-5.2.0, origin/16-latest) Fix cursor quoting in FetchStmt (#267)`
err when `make extract_source` directly
```
...... The previous output was omitted

# Avoid problems with static asserts
echo "#undef StaticAssertDecl" >> /mnt/d/projects/libpg_query/tmp/postgres/src/include/c.h
echo "#define StaticAssertDecl(condition, errmessage)" >> /mnt/d/projects/libpg_query/tmp/postgres/src/include/c.h
# Add pg_config.h overrides
cat scripts/pg_config_overrides.h >> /mnt/d/projects/libpg_query/tmp/postgres/src/include/pg_config.h
# Only define strlcpy when needed
sed -i "" 's/\#include "c.h"/#include "c.h"\n#if HAVE_DECL_STRLCPY == 0/' /mnt/d/projects/libpg_query/tmp/postgres/src/port/strlcpy.c
sed: can't read s/\#include "c.h"/#include "c.h"\n#if HAVE_DECL_STRLCPY == 0/: No such file or directory
make: *** [Makefile:148: /mnt/d/projects/libpg_query/tmp/postgres] Error 2

```

### Need more info? I'm pleasure to provide it.

**Comment by lfittl** [comment]
@BugsGuru Thanks for the report - we currently don't support running the extraction script on Linux, though we could fix that.

What's the reason you're trying to re-extract? (its not needed to use the library, only for maintainers to update the source to newer Postgres versions)

**Comment by BugsGuru** [comment]
@lfittl Thank you for your answer. In what environment should I run it? On Mac? 

My purpose in doing this is to modify the Postgres source code gram.y to support some special syntax. Re extract and use in pg_query_go.

**Comment by lfittl** [comment]
> @lfittl Thank you for your answer. In what environment should I run it? On Mac?

Yes, we currently run the extract source on macOS ourselves. That said, its very possible a few modifications would allow running it on Linux (its basically the `sed` syntax being different between Linux and macOS, plus a few other minor issues).

**Comment by BugsGuru** [comment]
@lfittl Got, thank you so much!
