### ISSUE TITLE
Expose the PG_VERSION

### ISSUE THREAD

**Issue by lelit** [pganalyze/libpg_query#32]
It would be nice if the actual PG_VERSION the library was built could be programmatically queried thru a function, or even simpler by a constant string.

**Comment by lfittl** [comment]
@lelit Yup, thats a good idea - I think we could just hardcode that into https://github.com/lfittl/libpg_query/blob/9.5-latest/pg_query.h along with the library version itself.

I'm thinking a macro `#define PG_QUERY_POSTGRES_VERSION ...` might be easiest - would that work for you?

**Comment by lelit** [comment]
Sure, no problem!

Thank you for the nice library BTW: I wrote an [alternative Python wrapper](https://github.com/lelit/pg_query), on which I built a SQL prettifier... 😄

**Comment by lfittl** [comment]
@lelit Actually, what you need may already be in the library, thanks to Postgres:

https://github.com/lfittl/libpg_query/blob/9.5-latest/src/postgres/include/pg_config.h#L766
https://github.com/lfittl/libpg_query/blob/10-latest/src/postgres/include/pg_config.h#L759

Would it work for you to just access that directly?

**Comment by lelit** [comment]
If that's included, it should be enough. I will try and report back.

**Comment by lelit** [comment]
It's not included in pg_query.h: that isn't a problem for me, because since my module is statically built against libpg_query and I have its complete source available at compile time I can easily include the `pg_config.h` header and expose the PG_VERSION_NUM.

So, issue solved for me, thank you!

However, looking forward, you may still consider to _copy_ that value within `pg_query.h`, or expose it thru some new API: one day the library could be distribuited on (say) Debian as a binary `.deb` package and at that whatever link against libpq_query.so won't be able to determine that value.

**Comment by lfittl** [comment]
Good point - I think I'll come back to this in case someone else requires it as well. Leaving open for now.
