### ISSUE TITLE
postgresql 9.6

### ISSUE THREAD

**Issue by Fjmolinabravo** [pganalyze/libpg_query#33]
Hi!
Sorry for my english!! :(

I have no experience creating branchs or sharing code

For my project, I need to use your library (pg_query) with postgresql 6.3; then i made the next changes

1. In "Makefile", I did:
- PG_VERSION = 9.6.3
- Comments  the next lines (I did it manually)
     #cd $(PGDIR); patch -p1 < $(root_dir)/patches/01_parse_replacement_char.patch
     #cd $(PGDIR); patch -p1 < $(root_dir)/patches/02_normalize_alter_role_password.patch

Then I compile with "make" command; i fixed some errors as:
`src/postgres/src_backend_utils_misc_guc.c:1334:4: error: ‘max_function_args’ no se declaró aquí (no en una función)
   &max_function_args,
    ^~~~~~~~~~~~~~~~~
`
`src/postgres/src_backend_utils_misc_guc.c:174:13: aviso: se usa ‘assign_tcp_keepalives_idle’ pero nunca se define
 static void assign_tcp_keepalives_idle(int newval, void *extra);`
etc...

finally it run the test...but it display the next error:

`Makefile:106: fallo en las instrucciones para el objetivo 'test'
make: *** [test] Segmentation fault (core dumped) [Núcleo vaciado a un archivo]
`
When i run the programs in the examples directory (simple, simple_plpgsql, etc), there are not error; that is, its execution is correct

Can you help me?

Thank you in advance

**Comment by lfittl** [comment]
@Fjmolinabravo 9.6 is currently not part of the supported set - it requires some work to rebase the Postgres version, so its no surprise you ran into errors.

The next supported version (besides the current 9.5) will be Postgres 10 - you can find a work in progress branch here: https://github.com/lfittl/libpg_query/tree/10-latest

**Comment by Fjmolinabravo** [comment]
thanks for your answare

Congratulations for your work!!!
