### ISSUE TITLE
Question: json to sql?

### ISSUE THREAD

**Issue by tbasilio** [pganalyze/libpg_query#37]
Hi,

I apologize if this is the wrong place for the question. Is there a way to turn the JSON back into SQL?

Thanks

**Comment by lfittl** [comment]
@tbasilio Which language are you working in?

Right now the C library itself doesn't provide for deparsing (which is the process to turn the JSON parsetree back into SQL), but the Ruby library supports it (https://github.com/lfittl/pg_query#modifying-a-parsed-query-and-turning-it-into-sql-again) and some other languages also have support.

**Comment by tbasilio** [comment]
Hi,

This is perfect. Thank you for the responsiveness and contributing to this awesome project.

**Comment by lfittl** [comment]
@tbasilio Excellent, happy to hear :)
