### ISSUE TITLE
"Segmentation fault (core dumped)" 

### ISSUE THREAD

**Issue by D93** [pganalyze/libpg_query#42]
I try to compile a .c file with a long complex SQL statement (PostgresQL query) as follows:

```
#include <pg_query.h>
#include <stdio.h>

int main() {
  PgQueryParseResult result;

  result = pg_query_parse("with	'log dir(theta|alpha)' as (select dirichlet(theta,alpha,'topic') from topic ), 'log p(phi|beta)' as (with 'log dir(phi|beta)' as (select dirichlet(phi,beta,'word join topic_word using (word_id)') from word join topic_word using (word_id) ) select sum('log dir(phi|beta)') as 'log p(phi|beta)' from 'log dir(phi|beta)' ), 'log p(z|theta)' as (with 'log cat(z_m|theta)' as (select categorical(document_id,theta,'document join topic using (topic_id)') from document join topic using (topic_id) ) select sum('log cat(z_m|theta)') as 'log p(z|theta)' from 'log cat(z_m|theta)' ), 'log p(w|phi)' as (with 'log cat(w_n|phi_z_doc_n)' as (select categorical(word_instance_id,phi,'word_instance join document using(document_id) join topic_word using (topic_id,word_id)') from word_instance join document using(document_id) join topic_word using (topic_id,word_id) ) select sum('log cat(w_n|phi_z_doc_n)') as 'log p(w|phi)' from 'log cat(w_n|phi_z_doc_n)' ) select 'log dir(theta|alpha)' + 'log p(phi|beta)' + 'log p(z|theta)' + 'log p(w|phi)' as 'log p(w,z,phi,theta|alpha,beta)' from 'log dir(theta|alpha)', 'log p(phi|beta)', 'log p(z|theta)', 'log p(w|phi)' ");

  printf('%s\n', result.parse_tree);

  pg_query_free_parse_result(result);
}
```
I replaced all inner double quotation marks (") within the statement with single ones (') as it wouldn't be compileable otherwise. 
Then I get warnings like this: 

> osboxes@osboxes:~/libpg_query/examples$ cc -I.. -L.. long_statement.c -lpg_query
long_statement.c: In function ‘main’:
> long_statement.c:9:10: warning: multi-character character constant [-Wmultichar]
>    printf('%s\n', result.parse_tree);
>           ^~~~~~
> long_statement.c:9:10: warning: passing argument 1 of ‘printf’ makes pointer from integer without a cast [-Wint-conversion]
> In file included from long_statement.c:2:0:
> /usr/include/stdio.h:318:12: note: expected ‘const char * restrict’ but argument is of type ‘int’
>  extern int printf (const char *__restrict __format, ...);
>             ^~~~~~

.. and if I try to open the compiled result, there's an error:

> osboxes@osboxes:~/libpg_query/examples$ ./a.out
> Segmentation fault (core dumped)

Is there anything I'm doing wrong?

**Comment by lfittl** [comment]
@D93 I think you're passing in a character instead of a string to your `printf` method (as the compiler is trying to tell you).

Can you change the print line to this and retry:

```
printf("%s\n", result.parse_tree);
```

(as its in the README)

**Comment by D93** [comment]
As I worked on my project, the SQL statement above changed, so let me continue with a newer SQL query.

With your hint as below
`printf("%s\n", result.parse_tree);`
it was possible to make the _segmentation fault error_ go away. Nonetheless - and unfortunately - I cannot get the parser tree for my query. The compiled **parser tree is empty** ( **[ ]** ).
The statement seems to be syntactically correct for a PostgreSQL system (PostgreSQL 9.6.5 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.2.0-3ubuntu1) 7.2.0, 64-bit), when the inner double quotation marks (") within the statement are not replaced with single ones ('). I had to do this replacement of the quotation marks as I wouldn't have a compatible string for this c file structure otherwise. 

Details below:

the c file:
```
#include <pg_query.h>
#include <stdio.h>

int main() {
  PgQueryParseResult result;

  result = pg_query_parse("with 'log dir(theta|alpha)' as (select dirichlet_lpdf(theta,alpha) as 'log dir(theta|alpha)' from topic	), 'log p(phi|beta)' as (with 	'log dir(phi|beta)' as (select dirichlet_lpdf(phi,beta) as result from 	word join topic_word using (word_id) ) select	sum(result) as 'log p(phi|beta)' from	'log dir(phi|beta)'), 'log p(z|theta)' as (	with   	'log cat(z_m|theta)' as (select	categorical_lpmf(document_id,theta) as result from document join topic using (topic_id))	select	sum(result) as 'log p(z|theta)'        	from	'log cat(z_m|theta)'), 'log p(w|phi)' as (with   	'log cat(w_n|phi_z_doc_n)' as (	select	categorical_lpmf(word_instance_id,phi)	as result	from	word_instance	join document using(document_id) join topic_word using (topic_id,word_id) )     	select	sum(result) as 'log p(w|phi)'    from		'log cat(w_n|phi_z_doc_n)'		)select  'log dir(theta|alpha)'  + 'log p(phi|beta)'  + 'log p(z|theta)'  + 'log p(w|phi)'  as 'log p(w,z,phi,theta|alpha,beta)'from  'log dir(theta|alpha)',  'log p(phi|beta)',  'log p(z|theta)',  'log p(w|phi)' ");

  printf("%s\n", result.parse_tree);

  pg_query_free_parse_result(result);
}
```
There are no warnings during a compilation.
The output shows an empty parser tree:

> osboxes@osboxes:~/libpg_query/examples$ ./a.out
> []

I've already asked myself, whether this issue has anything to do with a replacement of all the inner double quotation marks (") within the statement with single ones (') as explained above.

**Comment by lfittl** [comment]
Fairly certain that due to the change of quotation style the query is not valid SQL anymore (`"` and `'` mean two very different things in SQL).

You would need to check for errors, like here: https://github.com/lfittl/libpg_query/blob/10-latest/examples/simple_error.c#L10

Is there a reason you are not using a higher-level language, e.g. Ruby - where there are bindings, and it might be easier to integrate? (see https://github.com/lfittl/pg_query)

**Comment by D93** [comment]
> Is there a reason you are not using a higher-level language, e.g. Ruby - where there are bindings, and it might be easier to integrate? (see https://github.com/lfittl/pg_query)

Well, in my case I try to use valid SQL queries (which can be executed) as a source to generate other code (e.g. a specification for machine learning applications):
`SQL queries -> parser trees -> a specification for another language.`
I could also use Ruby as well, is doesn't actually have to be C. But with Ruby I expect to face the same problem with a queries containing **"**-marks: 
`PgQuery.parse("SELECT ? FROM x WHERE y = ?")`

That said, I would like to know if there is any way to parse SQL queries with double quotation marks within them?

**Comment by lfittl** [comment]
@D93 The problem is that double quotation marks have a different syntactical meaning in SQL than single quotation marks.

For example, these two mean very different things:

```SELECT 'test' FROM x```

Selects a string of the value "test"

```SELECT "test" FROM x```

Selects the column "test" from table x

---

So this is not a matter of simply teaching the parser to treat them the same - we can't, really. Does that help / make sense?

**Comment by D93** [comment]
To bring the issue back and close this ticket:

I've had two sorts of mistakes.
The first one is using the wrong quotation marks, e.g. :
`with 'log dir(theta|alpha)' as`
is wrong, it should be 
`with "log dir(theta|alpha)" as`.
I've falsely replaced all the inner double quotation marks (") within the statement with single ones ('), and it was not correct.

The second sort of mistakes: _not_ escaping the double quotation marks (") within the otherwise syntactically correct SQL statement string. 
One should work with `\"` in C to prevent the string from being finalized an the wrong place.

I admit, these mistakes are somehow silly, but maybe this could be helpful for anyone who comes across the same problems.
