### ISSUE TITLE
deparsing

### ISSUE THREAD

**Issue by pyramation** [pganalyze/libpg_query#47]
I know a few libraries are based on this one I believe are manually writing deparsing code, but leveraging the native parsing, https://github.com/lfittl/pg_query and https://github.com/zhm/pg-query-parser to name a few.

Is there a way to currently `deparse` with pg_query that I'm unaware of?

I know postgres has a lot of this stuff internally (https://doxygen.postgresql.org/deparse_8c_source.html), and wondering if it would potentially benefit the community in general.

@lfittl thoughts or tips?

**Comment by lfittl** [comment]
@pyramation In general it would be good to make use of Postgres own deparsing, however there are two main reasons I can remember of the top of my head why I didn't pursue that direction:

1) Postgres own deparsing works with post-parse analysis parse trees (which have relation names mapped to actual relids, etc), whilst libpg_query only works with the raw parser output
    - My personal use case for this library is to use it as a basis for analyzing/fingerprinting SQL, and that use case requires that this can run outside of a running Postgres server (due to roundtrip costs, etc)
   - Working with a post-parse analysis parse tree would (most likely) require a running Postgres server that actually had the tables/etc created that are referenced by the query, and is thus a very different problem that what pg_query is trying to solve

2) libpg_query currently only goes from Postgres-internal structs => JSON, but not the other way (see https://github.com/lfittl/libpg_query/blob/10-latest/src/pg_query_json.c and https://github.com/lfittl/libpg_query/blob/10-latest/scripts/generate_json_outfuncs.rb)
    - JSON in general is not the best interchange format, since its quite expensive to parse - my current thought is to actually work on a Protobuf-based format instead and handle conversion back into Postgres-internal structs through that

Hope that helps :)

**Comment by pyramation** [comment]
thanks for the reply! Sounds like very good reasons, and there is not yet a simple way to implement deparse using native posgres. 

I'll take a look at those links, thanks @lfittl!

**Comment by lfittl** [comment]
Closing this since deparsing has been implemented :)

**Comment by pyramation** [comment]
👏🏻👏🏻👏🏻👏🏻👏🏻  wow! Will have to integrate this, thank you!
