### ISSUE TITLE
determining enum constants mapping

### ISSUE THREAD

**Issue by pyramation** [pganalyze/libpg_query#48]
When I upgraded to the latest version many of the `objtype` numbers changed on nodes. 

I'm trying to find a programatic way to determine the mapping so I can go back and forth between representations. Currently it seems that some of the objtype numbers are coming from the `ObjectType` enum data structure in the original source, but some are not. 

For example, take these two statements as an example:

```
COMMENT ON CAST (text AS int4) IS 'Allow casts from text to int4';
COMMENT ON TABLE my_schema.my_table IS 'Employee Information';
```

the `CommentStmt` empirically yields an`OBJECT_CAST` since the node has `objtype=5`, which is correct! The other node yields `OBJECT_STATISTIC_EXT`  because `objtype=37`, however, we know it is actually supposed to be `OBJECT_TABLE`.

if you look below in the source, that's not exactly the order of the enums. Any idea why this is the case? I'm not sure if the node type would change the objtype, as I imagine they are shared throughout the source.

inside of `src/include/nodes/parsenodes.h`
https://doxygen.postgresql.org/parsenodes_8h.html#a842c5e2e69277690b064bf363c017980

```c
{
     OBJECT_ACCESS_METHOD,
     OBJECT_AGGREGATE,
     OBJECT_AMOP,
     OBJECT_AMPROC,
     OBJECT_ATTRIBUTE,           /* type's attribute, when distinct from column */
     OBJECT_CAST,
     OBJECT_COLUMN,
     OBJECT_COLLATION,
     OBJECT_CONVERSION,
     OBJECT_DATABASE,
     OBJECT_DEFAULT,
     OBJECT_DEFACL,
     OBJECT_DOMAIN,
     OBJECT_DOMCONSTRAINT,
     OBJECT_EVENT_TRIGGER,
     OBJECT_EXTENSION,
     OBJECT_FDW,
     OBJECT_FOREIGN_SERVER,
     OBJECT_FOREIGN_TABLE,
     OBJECT_FUNCTION,
     OBJECT_INDEX,
     OBJECT_LANGUAGE,
     OBJECT_LARGEOBJECT,
     OBJECT_MATVIEW,
     OBJECT_OPCLASS,
     OBJECT_OPERATOR,
     OBJECT_OPFAMILY,
     OBJECT_POLICY,
     OBJECT_PROCEDURE,
     OBJECT_PUBLICATION,
     OBJECT_PUBLICATION_REL,
     OBJECT_ROLE,
     OBJECT_ROUTINE,
     OBJECT_RULE,
     OBJECT_SCHEMA,
     OBJECT_SEQUENCE,
     OBJECT_SUBSCRIPTION,
     OBJECT_STATISTIC_EXT,
     OBJECT_TABCONSTRAINT,
     OBJECT_TABLE,
     OBJECT_TABLESPACE,
     OBJECT_TRANSFORM,
     OBJECT_TRIGGER,
     OBJECT_TSCONFIGURATION,
     OBJECT_TSDICTIONARY,
     OBJECT_TSPARSER,
     OBJECT_TSTEMPLATE,
     OBJECT_TYPE,
     OBJECT_USER_MAPPING,
     OBJECT_VIEW
 } ObjectType;
```
Is this where the `objtype`s are even coming from?

any help is appreciated! Currently I'm thinking to manually write test cases for each `objtype` and empirically discover them all at this point.

**Comment by lfittl** [comment]
I didn't double check, but pretty sure its just the ordering of the enum.

For your example, `The other node yields OBJECT_STATISTIC_EXT because objtype=37, however, we know it is actually supposed to be OBJECT_TABLE.` - I don't see how it does.

Taking https://github.com/postgres/postgres/blob/REL_10_STABLE/src/include/nodes/parsenodes.h#L1611 the 38th element (taking into consideration that the first element is 0), is `OBJECT_TABLE`, as it should be.

Another way of accessing this mapping btw is through the `enum_defs.json` file - see https://github.com/lfittl/libpg_query/blob/10-latest/srcdata/enum_defs.json#L387 (note that you need to ignore any element that doesn't have a name)

For example, in Ruby you could do the following:

```ruby
require 'json'
enum_defs = JSON.parse(File.read('enum_defs.json'))
enum_defs['nodes/parsenodes']['ObjectType']['values'].select { |e| e.key?('name') }[37]

=> {"name"=>"OBJECT_TABLE", "comment"=>nil}
```

**Comment by pyramation** [comment]
This is exactly what I was looking for!! Amazing. And your link is the right one. The doxygen link I posted must have been another version of postgres.

Thanks @lfittl this is super solid!
