### ISSUE TITLE
[Bug] Will occasionally run into errors on functioning queries.

### ISSUE THREAD

**Issue by ExSidius** [pganalyze/libpg_query#54]
This is in the normalize function.

Input: "SELECT * FROM banana"

Error - (signal: 11, SIGSEGV: invalid memory reference)

Occasionally, there is also a syntax error.

Let me know how I can help you resolve this issue.

**Comment by lfittl** [comment]
Hi @ExSidius - thanks for the report!

Are you saying that with the same input, if you run the normalize function many times, it sometimes crashes or returns a syntax error?

Which operating system are you testing on?

When you get the segfault, could you attempt to gather a backtrace, so we know which function caused the crash?

Thanks!

**Comment by ExSidius** [comment]
@lfittl That's correct. I'm testing on macOS Mojave.

On it.

**Comment by ExSidius** [comment]
I apologize. It seems that when I try to recreate it in C, I'm unable to. I'm currently working on bindings for the library. It's probably something on the FFI side of things. I appreciate how prompt your response was!
