### ISSUE TITLE
any plans to upgrade to 11 or 12?

### ISSUE THREAD

**Issue by pyramation** [pganalyze/libpg_query#66]
Hello @lfittl !

Hope you're doing well, it's been a while! I've been building a parser that relies on this library, and I've started to notice some differences now that I'm using 11.2. Do you think you'll be adding support for newer versions?

context, here's the old thread we were on...  https://github.com/zhm/node-pg-query-native/issues/9 my plan is to keep upgrading each release pg_query has :)

**Comment by beeing** [comment]
Yes, I'm interested as well as PG 12 supports `WITH xx AS MATERIALIZED(...)`.

**Comment by gmr** [comment]
And 13 :)

**Comment by flavius** [comment]
13 Anyone?

**Comment by lfittl** [comment]
Closing this, since pg_query 2.0 has been released with Postgres 13 support: https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser
