### ISSUE TITLE
Source data for BoolExprType is missing "NOT_EXPR"

### ISSUE THREAD

**Issue by autarch** [pganalyze/libpg_query#74]
I'm not sure how this happened, but it's missing the `NOT_EXPR` type.

**Comment by pyramation** [comment]
`AND_EXPR`, and `OR_EXPR` present, but not `NOT_EXPR`. I'm guessing `NOT_EXPR` must be equal to 2? I found this empirically in my deparser.

**Comment by lfittl** [comment]
This has been resolved in the v13 branch (due to be released in 1-2 weeks). The failure here was that the enum handling didn't consider multiple values on the same line.
