### ISSUE TITLE
Missing ppc atomics

### ISSUE THREAD

**Issue by pkubaj** [pganalyze/libpg_query#78]
Compiling libpg_query on powerpc64 platform results in:
```
./src/postgres/include/port/atomics.h:74:10: fatal error: 'port/atomics/arch-ppc.h' file not found
#include "port/atomics/arch-ppc.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by stanhu** [comment]
Probably just need to submit a pull request with a similar fix to https://github.com/lfittl/libpg_query/commit/0ce345469fac1f8cfa8b3d9f6a9af68d4550a5d1?

**Comment by pkubaj** [comment]
PR submitted.
