### ISSUE TITLE
Compute query_id from pg_stat_statements

### ISSUE THREAD

**Issue by stanhu** [pganalyze/libpg_query#95]
We use `pg_stat_statements` to gather the most time-consuming queries and use the `query_id` to identify them. This `query_id` is implemented here:

1. https://github.com/postgres/postgres/blob/54bb91c30e3964fd81059e6b02e377cc9dd2d64c/contrib/pg_stat_statements/pg_stat_statements.c#L17-L28
2. https://github.com/postgres/postgres/blob/54bb91c30e3964fd81059e6b02e377cc9dd2d64c/contrib/pg_stat_statements/pg_stat_statements.c#L2676-L2709

We also use `pg_query` to normalize and produce the `fingerprint` for each query in the slow logs, but it would be nice if we could also cross-reference the same queries by computing the `query_id`.

We could go the reverse and calculate the `fingerprint` from the `pg_stat_statements` output, but sometimes the query is truncated due to a limit setting in PostgreSQL.

**Comment by lfittl** [comment]
@stanhu Hah, yeah - you have the exact same use case here as we have at pganalyze :)

Its unfortunately not really possible to calculate the `query_id` outside the running Postgres server, as it is calculated based on information such as the relation OIDs, as well as dependent on the structure of the post-parse analysis query tree in Postgres (which you can't really reproduce outside of a running Postgres server).

Therefore the recommended approach here is to run the fingerprint method on the `query` field in `pg_stat_statements` (that is the same we do in pganalyze as well), and essentially discard the `query_id` information.

Hope that helps! - feel free to send me an email to lukas@pganalyze.com as well if you have any more detailed questions.

**Comment by stanhu** [comment]
@lfittl Ok, thanks so much for that information and for this library!
