### ISSUE TITLE
pg_query_parse exit  under multithread 

### ISSUE THREAD

**Issue by hcheng2002cn** [pganalyze/libpg_query#97]
hi,

pg_query_parse will exit(2) under multithreaded environment. the sql is wrong syntax. 
the branch is 12-latest.

```
#include <pg_query.h>
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

void *myThreadFun()
{
	PgQueryParseResult result;
	result = pg_query_parse("Select count(* from erroe");
	if (result.error) {
		printf("error: %s at %d\n", result.error->message, result.error->cursorpos);
	} else {
		printf("%s\n", result.parse_tree);
	}	
	pg_query_free_parse_result(result);
        return NULL;    
}

int main() {
  int i;
    pthread_t tid;
  
    // Let us create three threads
    for (i = 0; i < 3; i++)
        pthread_create(&tid, NULL, myThreadFun, NULL);
  
    pthread_exit(NULL);
    return 0;
}
```

result:
```
error: syntax error at or near "from" at 16
error occurred at scan.l:1181 before error message processing is available
error occurred at scan.l:1181 before error message processing is available
echo $?
2
```

**Comment by hcheng2002cn** [comment]
fixed after merging latest /src.

**Comment by lfittl** [comment]
> fixed after merging latest /src.

Thanks for the report, can you clarify whether this resolved on its own for you?

I can't reproduce this here on the latest 13-latest branch:

```
% test
error: syntax error at or near "from" at 16
error: syntax error at or near "from" at 16
error: syntax error at or near "from" at 16
```

**Comment by hcheng2002cn** [comment]
> > fixed after merging latest /src.
> 
> Thanks for the report, can you clarify whether this resolved on its own for you?
> 
> I can't reproduce this here on the latest 13-latest branch:
> 
> ```
> % test
> error: syntax error at or near "from" at 16
> error: syntax error at or near "from" at 16
> error: syntax error at or near "from" at 16
> ```

it's on 12_latest branch.  [this](https://github.com/bitdotioinc/libpg_query/blob/4162f839f0f7a77cb44fe8971684e791cc7716dd/src/pg_query.c#L8) fixed the bug.

Thanks for help.
hong
